# ===============================
# = Hibernate datasource
# ===============================

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_hibernate
    username: root
    password: rootroot
    # ===============================


    driver-class-name=com:
      mysql:
        jdbc:
          Driver
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


  thymeleaf:
    enabled=false
  # ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO





